#!/bin/bash -e

apt update
apt -y --no-upgrade install \
    python3 \
    python3-invoke \
    psutils \
    python3-psycopg2 \
    python3-psutil \
    postgresql-9.5 \
    python3-postgresql \
    python3-django \
    python3-django-tastypie \
    python3-django-extensions \
    python3-yaml \
    python3-mimeparse \
    python3-dateutil \
    python3-requests \
    python \
    python-selenium \
    python3-flake8 \
    pandoc \
    python3-pytest \
    python3-freezegun \
    python3-pip \
    python3-arrow \
    libjs-yui3-min \
    libjs-angularjs \
    libjs-yui \
    npm \
    python3-pyparsing \
    python3-pydot \
    python3-social-auth \
    python3-requests-oauthlib \
    python3-openid \
    python3-bs4 \
    nginx-full \
    gunicorn3 \
    postgresql-contrib \
    python-setuptools \
    --fix-missing

# export https_proxy=http://91.189.89.33:3128

echo "Installing packages via npm"
jslibs_dir="weebl/oilserver/static"
mkdir -p $jslibs_dir
npm install --prefix $jslibs_dir d3@^3.4.4 nvd3 angular-nvd3
chown -R $SUDO_ID:$SUDO_GID $jslibs_dir

echo "Done"
# unset https_proxy
